<?php namespace App\Controllers; use App\Core\Controller; use App\Core\CSRF; use App\Core\Helpers; use App\Core\Mailer; use App\Models\User; use App\Models\PasswordReset;
class AccountController extends Controller {
  private function requireAuth(){ if(!\App\Core\Auth::check()) $this->redirect('/login'); }
  public function show(){ $this->requireAuth(); $user=User::find((int)$_SESSION['uid']); $tpl='account/profile'; include __DIR__.'/../Views/layout.php'; }
  public function updateEmail(){ $this->requireAuth(); if(!CSRF::check($_POST['_csrf']??null)) die('Invalid CSRF'); $email=Helpers::sanitizeEmail($_POST['email']??''); if(!$email){ $_SESSION['flash']='Email invalide'; $this->redirect('/account'); } User::updateEmail((int)$_SESSION['uid'],$email); $_SESSION['uemail']=$email; $_SESSION['flash']='Email mis à jour'; $this->redirect('/account'); }
  public function requestPasswordCode(){ $this->requireAuth(); if(!CSRF::check($_POST['_csrf']??null)) die('Invalid CSRF'); $code=bin2hex(random_bytes(16)); PasswordReset::create((int)$_SESSION['uid'],$code,date('Y-m-d H:i:s', time()+900)); $link=rtrim($this->config['app_url'],'/').'/set-password?code='.$code; $html='<p>Code pour changer le mot de passe: <b>'.$code.'</b></p><p>Ou clique: <a href="'.$link.'">'.$link.'</a> (15 min)</p>'; Mailer::send($_SESSION['uemail'],'Code de changement de mot de passe',$html); $_SESSION['flash']='Code envoyé par email'; $this->redirect('/account'); }
  public function resetPassword(){ $this->requireAuth(); if(!CSRF::check($_POST['_csrf']??null)) die('Invalid CSRF'); $code=trim($_POST['code']??''); $pass=trim($_POST['password']??''); if(!$code || strlen($pass)<6){ $_SESSION['flash']='Code ou mot de passe invalide'; $this->redirect('/account'); } $uid=PasswordReset::consume($code); if(!$uid || $uid!=(int)$_SESSION['uid']){ $_SESSION['flash']='Code invalide/expiré'; $this->redirect('/account'); } User::updatePassword((int)$_SESSION['uid'], password_hash($pass, PASSWORD_BCRYPT)); $_SESSION['flash']='Mot de passe changé'; $this->redirect('/account'); }
  public function setPasswordForm(){ $code=trim($_GET['code']??''); $tpl='account/set_password'; include __DIR__.'/../Views/layout.php'; }
  public function setPasswordApply(){ if(!CSRF::check($_POST['_csrf']??null)) die('Invalid CSRF'); $code=trim($_POST['code']??''); $pass=trim($_POST['password']??''); if(!$code || strlen($pass)<6){ $_SESSION['flash']='Code ou mot de passe invalide'; $this->redirect('/set-password?code='.urlencode($code)); } $uid=PasswordReset::consume($code); if(!$uid){ $_SESSION['flash']='Code invalide/expiré'; $this->redirect('/set-password?code='.urlencode($code)); } User::updatePassword($uid, password_hash($pass,PASSWORD_BCRYPT)); $_SESSION['flash']='Mot de passe défini. Vous pouvez vous connecter.'; $this->redirect('/login'); }
}